-- Zetamax v1 — leagues
-- Replaces the pairwise friendships model with a group concept:
-- one league = many members; share the slug URL to invite anyone.
-- Leaderboard ranks members by their best score over the last 30 days.
--
-- Idempotent: safe to re-run.

-- ============================================================================
-- Drop the previous friend-graph model. No real data exists yet, so we wipe
-- cleanly rather than write a friendships → leagues migration path.
-- ============================================================================
DROP FUNCTION IF EXISTS public.get_friend_leaderboard(date);
DROP TABLE IF EXISTS public.friendships CASCADE;
DROP TABLE IF EXISTS public.invite_tokens CASCADE;

-- ============================================================================
-- leagues: one row per friend group. The slug is the shareable join URL —
-- a random 8-char base32 string generated by the API, unique across all
-- leagues. Anyone with the slug can join (open by default).
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.leagues (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  slug text NOT NULL UNIQUE,
  name text NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 64),
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_leagues_slug ON public.leagues (slug);

-- ============================================================================
-- league_members: one row per (league, user). Composite PK gives idempotent
-- joins — re-joining the same league is a no-op.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.league_members (
  league_id uuid NOT NULL REFERENCES public.leagues(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  joined_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (league_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_league_members_user
  ON public.league_members (user_id, joined_at DESC);

-- ============================================================================
-- is_league_member(): RLS helper. SECURITY DEFINER lets a non-member call
-- it (and get FALSE) without RLS recursion on league_members.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.is_league_member(lid uuid)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.league_members
    WHERE league_id = lid AND user_id = auth.uid()
  );
$$;

GRANT EXECUTE ON FUNCTION public.is_league_member(uuid) TO authenticated;

-- ============================================================================
-- RLS — defense in depth. Most writes go through service-role route handlers
-- that bypass RLS, but the policies catch any client-direct path.
-- ============================================================================
ALTER TABLE public.leagues ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.league_members ENABLE ROW LEVEL SECURITY;

-- leagues: any authenticated user can read (the slug is the gate — random
-- and unguessable; if you have it, you're invited).
DROP POLICY IF EXISTS leagues_select ON public.leagues;
CREATE POLICY leagues_select ON public.leagues
  FOR SELECT USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS leagues_insert_creator ON public.leagues;
CREATE POLICY leagues_insert_creator ON public.leagues
  FOR INSERT WITH CHECK (created_by = auth.uid());

-- league_members: read your own row + members of leagues you belong to.
-- Non-members can NOT enumerate other members directly; the leaderboard
-- and preview RPCs gate that explicitly.
DROP POLICY IF EXISTS league_members_select ON public.league_members;
CREATE POLICY league_members_select ON public.league_members
  FOR SELECT USING (
    user_id = auth.uid() OR public.is_league_member(league_id)
  );

DROP POLICY IF EXISTS league_members_insert_self ON public.league_members;
CREATE POLICY league_members_insert_self ON public.league_members
  FOR INSERT WITH CHECK (user_id = auth.uid());

-- ============================================================================
-- get_league_preview(slug): for the join page. Returns name + member count
-- + whether the caller is already a member. Callable by any authed user.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.get_league_preview(league_slug text)
RETURNS TABLE(
  league_id uuid,
  name text,
  member_count integer,
  is_member boolean
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    l.id,
    l.name,
    (SELECT count(*)::int FROM public.league_members WHERE league_id = l.id),
    EXISTS (
      SELECT 1 FROM public.league_members
      WHERE league_id = l.id AND user_id = auth.uid()
    )
  FROM public.leagues l
  WHERE l.slug = league_slug
  LIMIT 1;
$$;

GRANT EXECUTE ON FUNCTION public.get_league_preview(text) TO authenticated;

-- ============================================================================
-- get_my_leagues(): list-page query. Returns the caller's leagues with each
-- league's total member count and the caller's joined_at.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.get_my_leagues()
RETURNS TABLE(
  league_id uuid,
  slug text,
  name text,
  member_count integer,
  joined_at timestamptz
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    l.id,
    l.slug,
    l.name,
    (SELECT count(*)::int FROM public.league_members WHERE league_id = l.id),
    me.joined_at
  FROM public.leagues l
  JOIN public.league_members me ON me.league_id = l.id
  WHERE me.user_id = auth.uid()
  ORDER BY me.joined_at DESC;
$$;

GRANT EXECUTE ON FUNCTION public.get_my_leagues() TO authenticated;

-- ============================================================================
-- get_league_leaderboard(slug): the primary leaderboard query.
--
-- Each row: one member of the league, with their best score over the past
-- 30 days and how many qualifying runs they played in that window. Members
-- with zero qualifying runs still appear (best=0, runs=0).
--
-- Sort: best_score DESC, tie-broken by earliest started_at (first to reach
-- the score wins). Score floor: 5 (filters accidental opens).
--
-- The CTE 'lg' resolves the league only if the caller is a member, so non-
-- members get an empty result regardless of slug knowledge.
-- ============================================================================
CREATE OR REPLACE FUNCTION public.get_league_leaderboard(league_slug text)
RETURNS TABLE(
  user_id uuid,
  display_name text,
  avatar_url text,
  best_score integer,
  best_started_at timestamptz,
  runs_played integer
)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  WITH lg AS (
    SELECT l.id
    FROM public.leagues l
    JOIN public.league_members lm ON lm.league_id = l.id
    WHERE l.slug = league_slug
      AND lm.user_id = auth.uid()
    LIMIT 1
  ),
  members AS (
    SELECT lm.user_id
    FROM public.league_members lm
    JOIN lg ON lg.id = lm.league_id
  ),
  qualifying_runs AS (
    SELECT r.user_id, r.score, r.started_at
    FROM public.runs r
    WHERE r.user_id IN (SELECT user_id FROM members)
      AND r.validation_status = 'ok'
      AND r.score >= 5
      AND r.started_at >= now() - interval '30 days'
  ),
  best_runs AS (
    SELECT DISTINCT ON (qr.user_id)
      qr.user_id,
      qr.score AS best_score,
      qr.started_at AS best_started_at
    FROM qualifying_runs qr
    ORDER BY qr.user_id, qr.score DESC, qr.started_at ASC
  ),
  counts AS (
    SELECT qr.user_id, count(*)::int AS n
    FROM qualifying_runs qr
    GROUP BY qr.user_id
  )
  SELECT
    m.user_id,
    COALESCE(
      u.raw_user_meta_data->>'name',
      u.raw_user_meta_data->>'full_name',
      split_part(u.email, '@', 1)
    ) AS display_name,
    u.raw_user_meta_data->>'avatar_url' AS avatar_url,
    COALESCE(br.best_score, 0) AS best_score,
    br.best_started_at,
    COALESCE(c.n, 0) AS runs_played
  FROM members m
  JOIN auth.users u ON u.id = m.user_id
  LEFT JOIN best_runs br ON br.user_id = m.user_id
  LEFT JOIN counts c ON c.user_id = m.user_id
  ORDER BY best_score DESC, best_started_at ASC NULLS LAST
  LIMIT 50;
$$;

GRANT EXECUTE ON FUNCTION public.get_league_leaderboard(text) TO authenticated;
